apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: backend
  name: backend
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: backend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/greenpeace-hack/gp-node-be.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
    type: Source
  triggers:
  - imageChange:
      lastTriggeredImageID: docker-registry.default.svc:5000/openshift/nodejs@sha256:74a3ef2964efc03dfc239da3f09691b720ce54ff4bb47588864adb222133f0fc
    type: ImageChange
  - type: ConfigChange
  - generic:
      secret: 899c34bd6e69266d
    type: Generic
  - github:
      secret: 272590adedb9331c
    type: GitHub
status:
  lastVersion: 1
