apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    deploymentconfig: backend
  strategy:
    activeDeadlineSeconds: 21600
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
        deploymentconfig: backend
    spec:
      containers:
      - image: docker-registry.default.svc:5000/p4-dev/backend@sha256:cc92fe993571c446f52ee024ac24e8575617a6fe24ae8db188ec98ac14f4a571
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - backend
      from:
        kind: ImageStreamTag
        name: backend:latest
        namespace: p4-dev
      lastTriggeredImage: docker-registry.default.svc:5000/p4-dev/backend@sha256:cc92fe993571c446f52ee024ac24e8575617a6fe24ae8db188ec98ac14f4a571
    type: ImageChange
  - type: ConfigChange
